dist: xenial

language: java
install: ant deps
install: true

matrix:
  include:
  - jdk: oraclejdk9

script:
  - git config --global push.default simple
  - export GIT_TAG=$TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER
  - ant clean 
  - ant compile
  - ant jar
  - ant run
  
  
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER
  - echo "Just generated GIT_TAG for $TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER" >> $TRAVIS_BUILD_DIR/build.txt
  
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$GITPERM@github.com/CS3398-TState-Edosians/Java_Gradle_Hello_World  --tags
#  - ls -R



deploy:
  provider: releases
  api_key:
     $GITPERM
  file:
    - README.md
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
